openapi: 3.0.0
info:
  title: OCA Repository
  description: ''
  version: 1.0.0
servers:
  - url: http://localhost:9292/api/v1
tags:
  - name: namespaces
  - name: search

paths:
  /namespaces:
    post:
      summary: Creates a manageable namespace
      tags: [namespaces]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                namespace:
                  type: string
              required:
                - namespace
      responses:
        '200':
          description: Namespace created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad request, e.g. missing required parameter or invalid parameter value
        '500':
          description: Internal server error, e.g. database or system error

  /namespaces/{namespace}/bundles:
    get:
      summary: Returns a list of OCA Bundles with limit and offset
      tags: [namespaces]
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 0
            default: 20
            description: Maximum number of bundles to return
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
            default: 0
            description: Number of bundles to skip before starting to return results
      responses:
        '200':
          description: List of OCA Bundles returned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  bundles:
                    type: array
                    items:
                      type: object
                      properties:
                        said:
                          type: string
                          description: Self-Addressing IDentifier (SAID) of the bundle
                        version:
                          type: integer
                          description: Version of the bundle
        '400':
          description: Bad request, e.g. missing required parameter or invalid parameter value
        '404':
          description: Namespace not found
        '500':
          description: Internal server error, e.g. database or system error

    post:
      summary: Creates an OCA Bundle from OCAfile
      tags: [namespaces]
      security:
        - namespaceToken: []
      parameters:
        - in: path
          name: namespace
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ocafile:
                  type: object
                  description: CESR-based OCAfile
              required:
                - ocafile
      responses:
        '201':
          description: OCA Bundle created successfully
        '400':
          description: Bad request, e.g. missing required parameter or invalid parameter value
        '404':
          description: Namespace not found
        '500':
          description: Internal server error

  /namespaces/{namespace}/bundles/{said}:
    get:
      summary: Get OCA Bundle
      tags: [namespaces]
      parameters:
        - name: namespace
          in: path
          required: true
          description: Namespace identifier
          schema:
            type: string
        - name: said
          in: path
          required: true
          description: OCA Bundle SAID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Bundle not found

    put:
      summary: Update OCA Bundle
      tags: [namespaces]
      security:
        - namespaceToken: []
      parameters:
        - name: namespace
          in: path
          required: true
          description: Namespace identifier
          schema:
            type: string
        - name: said
          in: path
          required: true
          description: OCA Bundle SAID
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ocafile:
                  type: object
                  description: CESR-based OCAfile
              required:
                - ocafile
      responses:
        '200':
          description: OCA Bundle updated successfully
        '404':
          description: OCA Bundle not found

  /namespaces/{namespace}/bundles/{said}/change-history:
    get:
      summary: Get change history for OCA Bundle
      tags: [namespaces]
      parameters:
        - name: namespace
          in: path
          required: true
          description: Namespace identifier
          schema:
            type: string
        - name: said
          in: path
          required: true
          description: OCA Bundle SAID
          schema:
            type: string
        - name: before
          in: query
          description: SAID for the bundle before the specified version
          schema:
            type: string
        - name: after
          in: query
          description: SAID for the bundle after the specified version
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Bundle not found


  /namespaces/{namespace}/bundles/{said}/ocafile:
    get:
      summary: Download OCAfile used to create the bundle
      tags: [namespaces]
      parameters:
        - name: namespace
          in: path
          required: true
          schema:
            type: string
          description: Namespace of the bundle
        - name: said
          in: path
          required: true
          schema:
            type: string
          description: SAID of the bundle
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /namespaces/{namespace}/bundles/{said}/archive:
    get:
      summary: Download human readable representation of the current bundle
      tags: [namespaces]
      parameters:
        - name: namespace
          in: path
          required: true
          schema:
            type: string
          description: Namespace of the bundle
        - name: said
          in: path
          required: true
          schema:
            type: string
          description: SAID of the bundle
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object

  /search:
    get:
      summary: Search for bundles by name and namespace
      tags: [search]
      parameters:
        - name: query
          in: query
          required: true
          description: The search query for bundle names
          schema:
            type: string
        - name: namespace
          in: query
          description: The namespace to search within
          schema:
            type: string
      responses:
        "200":
          description: A list of matching bundles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

components:
  securitySchemes:
    namespaceToken:
      type: http
      scheme: bearer
