openapi: 3.0.2
info:
  title: Semantic Engine
  description: ''
  version: 0.4.0
servers:
  - url: http://localhost:8000
tags:
  - name: OCA Repository
    description: Endpoints to manage the OCA Bundles


paths:
  /oca-bundle:
    post:
      tags: [OCA Repository]
      summary: Creates an OCA Bundle from OCAfile
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: OCA Bundle created successfully
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object
                  properties:
                    success:
                      type: boolean
                    said:
                      type: string

  /oca-bundle/{said}:
    get:
      tags: [OCA Repository]
      summary: Get OCA Bundle
      parameters:
        - name: said
          in: path
          required: true
          description: OCA Bundle SAID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Bundle not found

  /oca-bundle/{said}/steps:
    get:
      tags: [OCA Repository]
      summary: List OCAFile steps to get OCA Bundle
      parameters:
        - name: said
          in: path
          required: true
          description: OCA Bundle SAID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Bundle not found

components:
  securitySchemes:
    namespaceToken:
      type: http
      scheme: bearer
